Host: qikan.cqvip.com,
Connection: keep-alive,
Content-Length: 984,
Accept: text/html, */*; q=0.01,
X-Requested-With: XMLHttpRequest,
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36,
Content-Type: application/x-www-form-urlencoded; charset=UTF-8,
Origin: http://qikan.cqvip.com,
Referer: http://qikan.cqvip.com/Qikan/Search/Advance?from=index,
Accept-Encoding: gzip, deflate,
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,
Cookie: cookie_data,